setwd('/home/fazar/Downloads')
library(sqldf)
powerdata<-read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date = '2/2/2007' or Date = '1/2/2007'", header = TRUE, sep = ";")
closeAllConnections()
Sys.setlocale("LC_TIME", "en_US.UTF-8")
date<-as.Date(powerdata$Date, "%d/%m/%Y")
datetime<-paste(date, powerdata$Time)
datetimer<-strptime(datetime, "%Y-%m-%d %H:%M:%S")
png(filename = "plot4.png", width = 480, height = 480, units = "px")
par(mfrow = c(2,2))
plot(datetimer,powerdata$Global_active_power, xlab='', ylab = 'Global Active Power', type = "n")
lines(datetimer,powerdata$Global_active_power)
plot(datetimer, powerdata$Voltage, ylab = "Voltage", xlab = "datetime", type = "n")
lines(datetimer, powerdata$Voltage)
plot(datetimer,powerdata$Sub_metering_1, ylab = "Energy sub metering", xlab = "", type = "n")
lines(datetimer,powerdata$Sub_metering_1, col="black")
lines(datetimer,powerdata$Sub_metering_2, col="red")
lines(datetimer,powerdata$Sub_metering_3, col="blue")
legend("topright", bty = "n", y.intersp = 0.8, xjust = 1, lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(datetimer, powerdata$Global_reactive_power, ylab = "Global_reactive_power", xlab = "datetime", type= "n")
lines(datetimer, powerdata$Global_reactive_power)
dev.off()
