setwd('/home/fazar/Downloads')
library(sqldf)
powerdata<-read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date = '2/2/2007' or Date = '1/2/2007'", header = TRUE, sep = ";")
closeAllConnections()
png(filename = "plot1.png", width = 480, height = 480, units = "px")
hist(powerdata$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.off()
