setwd('/home/fazar/Downloads')
library(sqldf)
powerdata<-read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date = '2/2/2007' or Date = '1/2/2007'", header = TRUE, sep = ";")
closeAllConnections()
Sys.setlocale("LC_TIME", "en_US.UTF-8")
date<-as.Date(powerdata$Date, "%d/%m/%Y")
datetime<-paste(date, powerdata$Time)
datetimer<-strptime(datetime, "%Y-%m-%d %H:%M:%S")
png(filename = "plot2.png", width = 480, height = 480, units = "px")
plot(datetimer,powerdata$Global_active_power, xlab='', ylab = 'Global Active Power (kilowatts)', type = "n")
lines(datetimer,powerdata$Global_active_power)
dev.off()
